artifacts_root: artifacts

data:
  raw_data_input: notebooks/Telco-Customer-Churn.csv
  raw_data_path: artifacts/raw_data.csv
  train_data_path: artifacts/train_data.csv
  test_data_path: artifacts/test_data.csv

split:
  test_size: 0.2
  random_state: 42
  stratify_col: Churn

target:
  name: Churn

features:
  drop_columns:
    - customerID

artifacts:
  preprocessor_path: artifacts/preprocessor.pkl
  X_train_path: artifacts/X_train.npy
  X_test_path: artifacts/X_test.npy
  y_train_path: artifacts/y_train.npy
  y_test_path: artifacts/y_test.npy
  model_path: artifacts/model.pkl
  metrics_path: artifacts/metrics/metrics.json

model:
  name: logistic_regression
  params:
    max_iter: 2000
    class_weight: balanced