artifacts_root: artifacts

data:
  raw_data_input: notebooks/Telco-Customer-Churn.csv
  raw_data_path: artifacts/raw_data.csv
  train_data_path: artifacts/train_data.csv
  test_data_path: artifacts/test_data.csv

split:
  test_size: 0.2
  random_state: 42
  stratify_col: Churn

target:
  name: Churn